/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package lk06.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;

public class PanelCover extends javax.swing.JPanel {

    public PanelCover() {
        initComponents();
        setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
      @Override
    protected void paintComponent(Graphics grphcs) {
      Graphics2D g2 = (Graphics2D) grphcs;

// Create a gradient that starts with a soft light blue and transitions to a gentle pastel yellow
Color startColor = new Color(204, 229, 255); // Soft light blue (clean, fresh, and bright)
Color endColor = new Color(255, 255, 204); // Gentle pastel yellow (light, warm, and elegant)

// GradientPaint from top to bottom (vertical gradient)
GradientPaint gra = new GradientPaint(0, 0, startColor, 0, getHeight(), endColor);

// Apply the gradient paint to fill the entire background
g2.setPaint(gra);
g2.fillRect(0, 0, getWidth(), getHeight());

// Call the parent method to ensure the panel is drawn properly
super.paintComponent(grphcs);




    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
